name: merge if all checks passed
on:
  pull_request:
    types:
      - labeled
  check_suite:
    types:
      - completed
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@master"
        env:
          GITHUB_TOKEN: "${{ secrets.EXTERNAL_GITHUB_TOKEN }}"
          MERGE_LABELS: ":rocket: Ready to Merge"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          UPDATE_LABELS: ":rocket: Ready to Merge"
          UPDATE_METHOD: "rebase"
          MERGE_FORKS: "false"
