name: merge - rebasing branch if out of date

on:
  pull_request:
    types:
      - labeled
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.EXTERNAL_GITHUB_TOKEN }}"
          MERGE_LABELS: ":rocket: Ready to Merge"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          UPDATE_LABELS: ":rocket: Ready to Merge"
          UPDATE_METHOD: "rebase"
          MERGE_FORKS: "false"
          MERGE_RETRIES: 1
          MERGE_RETRY_SLEEP : 1000
          LOG: "TRACE"
